"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { fetchBooks } from "../services/api";
export default function Home() {
  const [books,setBooks]=useState([]), [loading,setLoading]=useState(true), [error,setError]=useState("");
  const [query,setQuery]=useState(""), [sort,setSort]=useState("rating"), [saved,setSaved]=useState([]), [onlySaved,setOnlySaved]=useState(false);
  useEffect(()=>{try {setSaved(JSON.parse(localStorage.getItem("shelf-saved")||"[]"));}catch{} fetchBooks().then(setBooks).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);
  const toggle=(id)=>{const next=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];setSaved(next);localStorage.setItem("shelf-saved",JSON.stringify(next));};
  const visible=books.filter(b=>`${b.title} ${b.author}`.toLowerCase().includes(query.toLowerCase())&&(!onlySaved||saved.includes(b.id))).sort((a,b)=>sort==="title"?a.title.localeCompare(b.title):Number(b.rating)-Number(a.rating));
  return <div className="library"><section className="hero"><div><span className="eyebrow">THE READER’S CORNER</span><h1>Your next great read<br/><em>starts here.</em></h1><p>Discover thoughtful books. Share honest reviews.<br/>Build a shelf that feels like you.</p><a href="#collection" className="primary">Explore the collection ↗</a></div><div className="hero-art" aria-hidden="true"><div className="book-spine">IDEAS</div><div className="book-spine second">STORIES</div><div className="book-spine third">DISCOVERY</div><span>One book. A thousand possibilities.</span></div></section><section id="collection"><div className="section-title"><div><span className="eyebrow">CURATED FOR CURIOUS MINDS</span><h2>The collection <small>{books.length} books</small></h2></div><button className={onlySaved?"chip active":"chip"} onClick={()=>setOnlySaved(!onlySaved)}>{onlySaved?"Show all books":"♡ My favourites"}</button></div><div className="toolbar"><label className="search">⌕ <input aria-label="Search books" placeholder="Search by title or author…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Sort books" value={sort} onChange={e=>setSort(e.target.value)}><option value="rating">Highest rated</option><option value="title">Title A–Z</option></select></div>{loading?<p role="status">Opening the bookshelf…</p>:error?<p role="alert" className="error">{error}. Please check the backend connection.</p>:<div className="book-grid">{visible.map((b,i)=><article className="book-card" key={b.id}><div className={`cover cover-${i%3}`}><span className="cover-label">THE READER’S EDITION</span><h3>{b.title}</h3><p>{b.author}</p><button className="save" aria-label={`${saved.includes(b.id)?"Unsave":"Save"} ${b.title}`} aria-pressed={saved.includes(b.id)} onClick={()=>toggle(b.id)}>{saved.includes(b.id)?"♥":"♡"}</button></div><div className="card-info"><span className="rating">★ {b.rating} <small>/ 5</small></span><h3>{b.title}</h3><p>{b.author}</p><Link href={`/book/${b.id}`}>Read & review ↗</Link></div></article>)}</div>}{!loading&&!error&&visible.length===0&&<p>No matching books. Try another search or save a favourite.</p>}</section></div>;
}
